(source gnu)
(source melpa)

(depends-on "chinese-pyim")
(depends-on "chinese-pyim-greatdict")
(depends-on "company")
(depends-on "counsel")
(depends-on "evil")
(depends-on "evil-leader")
(depends-on "hungry-delete")
(depends-on "monokai-theme")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "smartparens")
(depends-on "swiper")
(depends-on "window-numbering")
