;; Auto generated by `pyim-generate-dict-cache-file', don't edit it by hand!

#s(hash-table size 1000000 test equal rehash-size 1.5 rehash-threshold 0.8 data ("中文" (:count 2) "输入" (:count 3) "输入法" (:count 2)))
